services:

  app:
    image: arisesinmight/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./app:/root"
    command: make test
    depends_on: 
      - db
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
