services:

  app:
    image: arisesinmight/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ".env.example:/app/.env"
    command: make test
    depends_on: 
      - db
  db:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
