services:

  app:
    image: arisesinmight/docker-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ".env.example:/app/.env"
    command: make test
    depends_on: 
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
